### ISSUE TITLE
5002 parameter error zDispatchMap on IRIS 2023.1

### ISSUE THREAD

**Issue by annietongisc** [intersystems-ru/WorkflowAPI#4]
{
    "errors": [
        {
            "code": 5002,
            "domain": "%ObjectErrors",
            "error": "ERROR #5002: ObjectScript error: <PARAMETER>zDispatchMap^isc.wf.REST.1",
            "id": "ObjectScriptError",
            "params": [
                "<PARAMETER>zDispatchMap^isc.wf.REST.1"
            ]
        }
    ],
    "stack": {
        "objlasterror": "ERROR #5002: ObjectScript error: <PARAMETER>zDispatchMap^isc.wf.REST.1",
        "request": {
            "_class": "%CSP.Request",
            "URL": "/csp/workflow/rest/test",
            "PageName": "test",
            "URLPrefix": "",
            "UserAgent": "PostmanRuntime/7.30.1",
            "RequestId": "FE4",
            "NoResetTimeout": false,
            "ContentType": "",
            "CharSet": "",
            "Content": "",
            "Method": "GET",
            "Protocol": "HTTP/1.1",
            "Secure": false,
            "GatewayApplication": "/csp",
            "GatewayConnectionName": "LOCAL",
            "GatewaySessionIdSource": 3,
            "GatewayNewId": false,
            "GatewayBuild": "661.2301.1828",
            "GatewayFunctions": 7,
            "GatewaySessionCookie": "CSPSESSIONID-SP-52773-UP-csp-workflow-rest-",
            "GatewayInstanceName": "iris-db-vm:52773",
            "RegistryMethods": 1,
            "GatewayError": "",
            "Application": "/csp/workflow/rest/",
            "CSPGatewayRequest": true,
            "GatewayTimeout": 60,
            "AppData": "",
            "AppMatch": "/csp/workflow/rest/",
            "Class": "isc.wf.REST",
            "Service": "REST",
            "ProcessedRequestType": true
        },
        "response": {
            "_class": "%CSP.Response",
            "HTTPVersion": "",
            "Status": "500 Internal Server Error",
            "Redirect": "",
            "UseExactRedirect": false,
            "ServerSideRedirect": "",
            "ContentType": "application/json",
            "CharSet": "UTF-8",
            "CookiePath": "/csp/workflow/rest/",
            "HeaderCharSet": "",
            "ContentLength": "",
            "NoCharSetConvert": false,
            "UseHttpOnly": true,
            "InProgress": 1,
            "Expires": "Thu, 29 Oct 1998 17:04:19 GMT",
            "VaryByParam": "",
            "TraceDump": false,
            "OutputSessionToken": false,
            "UseASPredirect": false,
            "Timeout": "",
            "Language": "en",
            "Domain": "%UtilityLogin",
            "GzipOutput": null,
            "IgnoreRESTOutput": null,
            "AllowOutputFlush": 0,
            "AvoidPartitionCleanup": false
        },
        "stack": [
            {
                "call": "DO",
                "line": " 0",
                "part": ""
            },
            {
                "call": "DO",
                "line": "SuperServer+60^%SYS.SERVER 2",
                "part": "%SYS.SERVER"
            },
            {
                "call": "DO",
                "line": "css+21^%SYS.cspServer2 1",
                "part": "%SYS.cspServer2"
            },
            {
                "call": "DO",
                "line": "ProcessRequest+1^%CSP.Request.1 1",
                "part": "%CSP.Request.1"
            },
            {
                "call": "DO",
                "line": "Request+25^%SYS.cspServer2 1",
                "part": "%SYS.cspServer2"
            },
            {
                "call": "DO",
                "line": "Request+683^%SYS.cspServer2 1",
                "part": "%SYS.cspServer2"
            },
            {
                "call": "DO",
                "line": "ProcessRequest+1^%CSP.Session.1 1",
                "part": "%CSP.Session.1"
            },
            {
                "call": "DO",
                "line": "CSPDispatch+274^%SYS.cspServer 1",
                "part": "%SYS.cspServer"
            },
            {
                "call": "$$",
                "line": "CSPDispatch+495^%SYS.cspServer 2",
                "part": "%SYS.cspServer"
            },
            {
                "call": "DO",
                "line": "zPage+31^%CSP.REST.1 1",
                "part": "%CSP.REST.1"
            },
            {
                "call": "$$",
                "line": "Http500+1^%CSP.REST.1 1",
                "part": "%CSP.REST.1"
            },
            {
                "call": "DO",
                "line": "ReportHttpStatusCode+2^%CSP.REST.1 2",
                "part": "%CSP.REST.1"
            },
            {
                "call": "$$",
                "line": "zoutputStatus+6^isc.wf.REST.1 1",
                "part": "isc.wf.REST.1"
            },
            {
                "call": "$$",
                "line": "zgetDebugInfo+2^isc.wf.REST.1 1",
                "part": "isc.wf.REST.1"
            },
            {
                "call": "$$",
                "line": "zgetStackInfo+1^isc.wf.REST.1 1",
                "part": "isc.wf.REST.1"
            }
        ],
        "user": "ctong"
    },
    "summary": "ERROR #5002: ObjectScript error: <PARAMETER>zDispatchMap^isc.wf.REST.1"
}

IRIS version is IRIS for UNIX (Ubuntu Server 20.04 LTS for x86-64) 2023.1 (Build 229U)

**Comment by eduard93** [comment]
Hello!

I installed Workflow API on `IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2023.1 (Build 229U) Fri Apr 14 2023 17:37:52 EDT [Health:5.1.0]` and sending `GET /test` request returns expected: `{"Status": "OK"}`. 

However, I see that the error originates from `zDispatchMap^isc.wf.REST.1`, which means that `isc.wf.REST` class defines the `DispatchMap` method. But in the project [isc.wf.REST](https://github.com/intersystems-ru/WorkflowAPI/blob/master/isc/wf/REST.cls) does not redefine the `DispatchMap` method; it only inherits it from `%CSP.REST`.

I assume you did `DispatchMap` override.

When updating to a new version, I recommend reading [Release Notes](https://docs.intersystems.com/irislatest/csp/docbook/changes/index.html#REST) for the release. In this case, the `REST` section states:

> The code for dispatching requests in %CSP.REST was quite inefficient, particularly for Dispatch classes with a large number of routes. This change refactors the dispatch code to be more efficient and changes the signature of DispatchMap() method. 

`DispatchMap` signature in 2023.1 is: 

```
ClassMethod DispatchMap(pURL As %String, pMethod As %String, Output pResourceMatched As %Boolean, Output pMatcher As %Regex.Matcher) As %String [ CodeMode = objectgenerator ]
````

`DispatchMap` signature in 2022.1 is: 
```
ClassMethod DispatchMap(pIndex As %Integer) As %String [ CodeMode = generator ]
```

Please adjust `DispatchMap` implementation to be compatible with 2023.1 version. 

Alternatively, for what purpose do you redefine `DispatchMap`? `%CSP.REST` provides a variety of callbacks to implement your customization, it's recommended to use them instead of redefining core `Dispatch` methods. If you need to redefine `OnPreDispatch` or `Login` callbacks, already redefined by `isc.wf.REST`, you can do that by subclassing  `isc.wf.REST` and using [##super Syntax](https://docs.intersystems.com/iris20231/csp/docbook/DocBook.UI.Page.cls?KEY=GOBJ_specialcos#GOBJ_specialcos_lblbsuper).
